### ISSUE TITLE
README.md: env questions

### ISSUE THREAD

**Issue by garlick** [flux-framework/docs#6]
Just wondering if the following virtual environment command may be preferable to the one in the README.md?  I understand virtualenv is now built into python3 (as `venv`).   On a Ubuntu18.04 LTS system, `python` is actually python2, so running the commands in the README.md resulted in a python 2 environment.  I figured that was going to end badly, and in backing up, discovered this alternate method:

```
$ python3.6 -m venv --system-site-packages env
```

Also, maybe it would be better to tell people to use `_env` or `_sphinx_env`, add it to a "clean" or "veryclean" make target, and to .gitignore to underscore that it's not part of the project?

**Comment by garlick** [comment]
Actually (on second thought) this may not be appropriate for the Makefile or .gitignore if it's just a suggested way to satisfy the dependencies.  Maybe if a "make virtualenv" target was added?

Meh, whatever.  I'm an newbie here so feel free to close as an artifact of my learning process if irrelevant.

**Comment by garlick** [comment]
I also needed (in the venv)
```console
$ pip install sphinx_rtd_theme
```
for the `html` target to work.  Then pretty things popped out in my `_build` directory!

**Comment by SteVwonder** [comment]
> I also needed (in the venv) $ pip install sphinx_rtd_theme

We could put together a `requirements.txt` so that users (or a Makefile) can do `pip install -r requirements.txt` and it all "just work" :tm:. 

I'm not sure about the best solution for the virtualenv thing.  I (naively) assume that Sphinx still works with python2, although now that py2 is EOL'd, that might not be true for long.
